name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: libanalyze
      working-directory: ./libanalyze
      run: |
        cargo clippy
    - name: analyzer
      run: |
        cargo clippy
